### PR TITLE
support Scala 2.12.0-RC1

### PR DESCRIPTION
**Pull request by xuwei-k**

### CODE REVIEW

**Comment by axel22** [comment]
Quick heads-up: I'm currently publishing ScalaMeter for 2.12.0-RC1 using the 2.11 version of casbah, which means that casbah-related features won't work until this is published, and ScalaMeter re-published with the proper dependencies.

**Comment by rozza** [comment]
@xuwei-k Thanks for the ticket Casbah 3.1.1 has been pushed with Scala 2.12.0-RC1 support.

**Comment by rozza** [comment]
@axel22 thanks for the prod - I've pushed 3.1.1 for 2.12.0-RC1

**Comment by axel22** [comment]
@rozza Thanks a lot, I changed to the newest dependency!

**Comment by SethTisue** [comment]
added to https://github.com/scala/make-release-notes/blob/2.12.x/projects-2.12.md

**Pull request merged**
